# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc26def638e180772e36a6aba33a40d63dbf634bb276918cdb1b51fbd66b6f5f3e8ddf18ca8b0683be9ecd12b9d6c9432de7af05ad43d4d33702898aedcbd54b

test:
  secret_key_base: 4ba090d1ab1a5720efb163c68f40af08a820b6a6878bfc4de374fe3b6a159cefc4638ec8d06174afa1dfdb32d5a86ed1ff3df3f18b0f9ddd8fb06ff39e8df1df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
